name: action-composer
services:
  action-server:
    image: ghcr.io/joshyorko/action-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: action-server
    ports:
      - "8080:8080"
      - "8087:8087"
      - "3000:3000"
    volumes:
      - action-server-data:/action-server/datadir
    restart: unless-stopped
    environment:
      - RC_ACTION_SERVER_HOST=0.0.0.0
      - RC_ACTION_SERVER_PORT=8080

volumes:
  action-server-data: