# Required: A short name for the action package
name: Actions -Server-Demo
    
# Required: A description of what's in the action package.
description: Actions for setting up and managing other action packages.

# Required: The current version of this action package.
version: 1.0.3

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
  - python=3.10.16
  - uv=0.5.31
  pypi:
  - sema4ai-actions=1.3.3
  - requests=2.32.3
  - black=25.1.0
  - pytz=2025.1



packaging:
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip

